### ISSUE TITLE
integração com sistemas próprios

### ISSUE THREAD

**Issue by andremillet** [laboratoriobridge/esusab-integracao#12]
boa tarde. desculpa se usei o meio errado para contato.
sou médico da atenção primária, estou usando o esus CDS no linux
eu consigo integrar os dados do cds pra conseguir ter acesso aos relatorios de produação? ngm na secretaria de saude daqui sabe me informar e eu nao tenho acesso aos dados que eu mesmo gero. a unidade nao dispoe do PEC. 
gostaria de saber se conseguiria ter acesso a esses dados de alguma outra forma

**Comment by lucasmaysouza** [comment]
@andremillet bom dia, tudo bem?

Precisamos que você encaminhe sua dúvida para o e-mail "suporte@esusab.ufsc.br".
