### ISSUE TITLE
Campos "Educação" e "Saúde" não estão sendo persistidos

### ISSUE THREAD

**Issue by schenato** [laboratoriobridge/esusab-integracao#2]
Boa tarde, estou enfrentando um problema ao importar os dados para o sistema do e-SUS, o arquivo .zip foi gerado pelo sistema G-MUS e foi verificado que o mesmo está seguindo os padrões estabelecidos e que está enviando o valor desses dois campos. Porém ao gerar o relatório essas informações não constam no mesmo.

Gostaria que verificasse se a validação está correta. Caso alguém tenha enfrentado esse problema e solucionado de alguma forma, agradecemos qualquer dica.

Atenciosamente,
Gabriel Schenato
Inovadora Sistemas
Lages, SC

**Comment by lucasmaysouza** [comment]
@schenato bom dia.

Por gentileza, poderia nos passar um e-mail para contato?

Att,

Suporte Laboratório Bridge.

**Comment by schenato** [comment]
Bom dia, sim gabriel.schenato@inovadora.com.br

Atenciosamente,
Gabriel Schenato
Inovadora Sistemas
Lages, SC

**Comment by lucasmaysouza** [comment]
@schenato Conforme conversamos, o arquivo enviado possuía a descrição da versão 2.1.00. Alterando este valor para 3.0.00 o e-SUS AB PEC irá validar o arquivo conforme a versão mencionada.

**Comment by schenato** [comment]
Correto, obrigado.
Atenciosamente,
Gabriel Schenato
Inovadora Sistemas
Lages, SC
