### ISSUE TITLE
Instalador PEC 3.2.4

### ISSUE THREAD

**Issue by julianlfs** [laboratoriobridge/esusab-integracao#21]
Boa tarde, porque no [site](https://aps.saude.gov.br/ape/esus/download) ainda não tem a PEC/CDS versão 3.2.24? Alguma previsão? E a PEC 4.0.0?

Obrigado

**Comment by lucasmaysouza** [comment]
Julian, boa tarde.

Tudo bem?

Agora a SAPS dispõe de um novo canal de suporte para registrar suas demandas relacionadas à Estratégia e-SUS APS. É fácil e intuitivo, assim como o e-SUS! Aproveite e insira esta demanda lá!

Faça o cadastro no portal e registre sua solicitação: bit.ly/SuporteAPSeSUS

Ficamos à disposição.
