### ISSUE TITLE
Atualizar Thrift para LEDI AB 4.0.0

### ISSUE THREAD

**Issue by tonybolzan** [laboratoriobridge/esusab-integracao#23]
Gostaríamos de atualizar os layouts de transmissão para a versão LEDI AB 4.0.0
Mas para isso precisamos dos arquivos thrift atuais

**Comment by fernandobt8** [comment]
O LEDI AB 4.0.0 só possui alterações de validações, por isso não é necessário qualquer atualização no arquivos thrift atuais, [aqui](https://integracao.esusab.ufsc.br/ledi/documentacao/principais_alteracoes.html) você pode as mudanças da última versão para a nova.
