### ISSUE TITLE
Como funciona a compilação para diversas linguagens via Thrift?

### ISSUE THREAD

**Issue by o-leolleo** [laboratoriobridge/esusab-integracao#37]
Oi, pessoal, estou trabalhando com um sistema que utiliza este repositório, em específico os arquivos php. Tem nos ajudado bastante, obrigado.

Queria tirar algumas dúvidas, porque pra gente seria interessante se pudéssemos compilar o thrift em um fluxo de CI/CD.  
Seria possível explicar como vocês fazem esse processo de geração dos thrifts para as linguagens?

**Comment by geidsonc** [comment]
Opa, @leolleocomp dá uma olhada no esusab-integracao/thrift/layout-ras/thrift_build.sh

**Comment by leolleocomp** [comment]
Rapaz! Agora tudo faz sentido! Valeu @geidsonc !
