### ISSUE TITLE
Campo antigo povoComunidadeTradicional na nova versão

### ISSUE THREAD

**Issue by schenato** [laboratoriobridge/esusab-integracao#52]
Na nova versão foi repassado:
1. Foi adicionado o campo codificado coPovoComunidadeTradicional e removido o campo de texto povoComunidadeTradicional.

Porém, no arquivo thrift/layout-ras/gen-javabean/br/gov/saude/esusab/ras/cadastroindividual/InformacoesSocioDemograficasThrift.java ainda está o campo antigo

**Comment by geidsonc** [comment]
Aguardando as mudanças
