### ISSUE TITLE
problemas com o previne brasil !!!

### ISSUE THREAD

**Issue by carlos-laurentino** [laboratoriobridge/esusab-integracao#56]
Bom dia, todos os xml do meu sistema tiveram como base os exemplos postados aqui até ai está tudo funcionando perfeitamente
agradeço a todos pela colaboração porque quando comecei não sabia nem por onde começar, mas agora me deparei com um problema os arquivos não geram informações para o previne brasil, meu cliente ficou com zerado no quadrimestre passado, preciso de um suporte urgente, vou deixar meu zap para contatos  e estou disposto a pagar pelo suporte.

(38) 99861 3246 - laurentinocarlos@gmail.com

**Comment by ggeraldeli** [comment]
Estamos fechando as issues desse repositório pois não são gerenciadas pela nossa equipe, caso o problema persista faça o cadastro no portal e registre sua solicitação: http://esusaps.bridge.ufsc.br/a/.
