### ISSUE TITLE
Ficha de atividade coletiva - Erro na ordenação

### ISSUE THREAD

**Issue by KelvinEger** [laboratoriobridge/esusab-integracao#57]
Na documentação da ficha versão Layout e-SUS APS de Dados e Interface Versão 4.2.3, o item: '#15headerTransport' vem antes de '#18pseEducacao' e '#19pseSaude', porém no XML de exemplo aqui do github os PSEs vem antes de HeaderTransport. 
Ao realizar as manutenções baseando-se no manual, alguns problemas ocorreram. Em teoria, a ordem não deveria estar interferindo a causando erros, mas existe a ocorrência dos mesmos.

**Comment by ggeraldeli** [comment]
Estamos fechando as issues desse repositório pois não são gerenciadas pela nossa equipe, caso o problema persista faça o cadastro no portal e registre sua solicitação: http://esusaps.bridge.ufsc.br/a/.
