### ISSUE TITLE
Ler arquivo .esus

### ISSUE THREAD

**Issue by statspy-ml** [laboratoriobridge/esusab-integracao#80]
Ola
Alguem pode me explicar como faço para deserializar um arquivo .esus?
Tenho uma ficha no formato .esus e gostaria de ler o registro. Como devo fazer?
Obrigado

**Comment by ggeraldeli** [comment]
Estamos fechando as issues desse repositório pois não são gerenciadas pela nossa equipe, caso o problema persista faça o cadastro no portal e registre sua solicitação: http://esusaps.bridge.ufsc.br/a/.
